#!/bin/bash

cd given_parser
export CLASSPATH="../lib/antlr-4.7.1-complete.jar:../lib/javax.json-1.0.4.jar:.:$CLASSPATH"
make clean
make
for d in ../benchmarks/* ; do
   java -ea MiniCompiler ${d}/`basename ${d}`.mini 
   cp ../output.ll ${d}/`basename ${d}`.ll
done
cd ..
